[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "docs-as-code workshop"
authors = [{name = "Petra", email = "petra@docs"}]
dynamic = ["version", "description"]
